source 'https://github.com/GetuiLaboratory/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

pod 'FMDB', '~> 2.7'

target 'FMDBDemo' do
    
end

target 'FMDBDemoTests' do
    
end

target 'FMDBDemoUITests' do
    
end
